resource "local_file" "inventory" {
  content = <<-EOT
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    # Node list

    [ycn1nginx]
    nginx ansible_host=${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}

    [ycn2master]
    master ansible_host=${yandex_compute_instance.ycn2master.network_interface.0.ip_address}

    [ycn3slave]
    slave ansible_host=${yandex_compute_instance.ycn3slave.network_interface.0.ip_address}

    [ycn4application]
    application ansible_host=${yandex_compute_instance.ycn4application.network_interface.0.ip_address}

    [ycn5gitlab]
    gitlab ansible_host=${yandex_compute_instance.ycn5gitlab.network_interface.0.ip_address}

    [ycn6runner]
    runner ansible_host=${yandex_compute_instance.ycn6runner.network_interface.0.ip_address}

    [ycn7monitoring]
    monitoring ansible_host=${yandex_compute_instance.ycn7monitoring.network_interface.0.ip_address}

    # Node group

    [allnodes:children]
    ycn1nginx
    ycn2master
    ycn3slave
    ycn4application
    ycn5gitlab
    ycn6runner
    ycn7monitoring

    [db:children]
    ycn2master
    ycn3slave

    # Vars for group and nodes
    [ycn1nginx:vars]
    domain = "${var.domain}"
    le_staging = "${var.lets_encrypt_staging}"

    [db:vars]
    replicator_passwd = "${var.replicator_passwd}"

    [ycn2master:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}"'
    mysql_replication_role = "master"

    [ycn3slave:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}"'
    mysql_replication_role = "slave"

    [ycn4application:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}"'
    domain = "${var.domain}"

    [ycn5gitlab:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}"'
    gitlab_passwd = "${var.gitlab_passwd}"
    gitlab_runner = "${var.gitlab_runner}"
    domain = "${var.domain}"

    [ycn6runner:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}"'
    gitlab_runner = "${var.gitlab_runner}"
    domain = "${var.domain}"

    [ycn7monitoring:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.ycn1nginx.network_interface.0.nat_ip_address}"'
    grafana_passwd = "${var.grafana_passwd}"

    [allnodes:vars]
    domain = "${var.domain}"
    ip_ycn1nginx = ${yandex_compute_instance.ycn1nginx.network_interface.0.ip_address}
    ip_ycn2master = ${yandex_compute_instance.ycn2master.network_interface.0.ip_address}
    ip_ycn3slave = ${yandex_compute_instance.ycn3slave.network_interface.0.ip_address}
    ip_ycn4application = ${yandex_compute_instance.ycn4application.network_interface.0.ip_address}
    ip_ycn5gitlab = ${yandex_compute_instance.ycn5gitlab.network_interface.0.ip_address}
    ip_ycn6runner = ${yandex_compute_instance.ycn6runner.network_interface.0.ip_address}
    ip_ycn7monitoring = ${yandex_compute_instance.ycn7monitoring.network_interface.0.ip_address}

    EOT
  filename = "../ansible/inventory.yml"
  file_permission = "0644"

  depends_on = [
    yandex_compute_instance.ycn1nginx,
    yandex_compute_instance.ycn2master,
    yandex_compute_instance.ycn3slave,
    yandex_compute_instance.ycn4application,
    yandex_compute_instance.ycn5gitlab,
    yandex_compute_instance.ycn6runner,
    yandex_compute_instance.ycn7monitoring
  ]
}
